# Generated by Django 4.1.13 on 2025-03-12 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
