# Generated by Django 4.1.13 on 2025-04-19 16:17

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.PositiveIntegerField(unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'student_login',
            },
        ),
    ]
