# Generated by Django 4.1.13 on 2025-04-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0002_studentlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlogin',
            name='dept',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentlogin',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
