# Generated by Django 4.1.13 on 2025-04-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0004_remove_post_author_post_author_email_post_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatar/'),
        ),
    ]
