# Generated by Django 4.1.13 on 2025-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
