# Generated by Django 4.1.13 on 2025-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0005_alumni_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='password',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='alumni_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatar/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/posts/'),
        ),
    ]
