# Generated by Django 4.1.13 on 2025-04-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0005_post_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='company',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='jobpost',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
