# Generated by Django 4.1.13 on 2025-04-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0006_alumni_password_alter_alumni_alumni_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='last_name',
        ),
    ]
