# Generated by Django 4.1.13 on 2025-04-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0007_remove_alumni_first_name_remove_alumni_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
