# Generated by Django 4.1.13 on 2025-04-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_site', '0008_remove_donation_donor_remove_donation_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumni_site.alumni'),
            preserve_default=False,
        ),
    ]
